### ISSUE TITLE
Mole calculation, in terms of n

### ISSUE THREAD

**Issue by Ho-Nothing** [SkyeWong/ChemNotes#1]
**Describe the error**
- 2 mole of O2 molecule -> atom

**Screenshots**
Add a screenshot of the mistake.
![Screenshot_20240107_140248_Chrome](https://github.com/SkyeWong/ChemNotes/assets/132768687/2fd4f466-42b5-4f48-8f97-0ae51c61506d)

**Additional context**
Skyw when hv gf

**Comment by SkyeWong** [comment]
this is fixed in commit a448062.

gf 就随遇而安吧 :(
